### ISSUE TITLE
Allow selecting a specific world region to render

### ISSUE THREAD

**Issue by Steffo99** [Steffo99/flyingsnake#1]
It could use arguments like
```
-x x_coord 
-y y_coord 
-w region_width 
-h region_height
```

**Comment by Steffo99** [comment]
Perhaps, more `@click.option()`s could be added here: 

https://github.com/Steffo99/flyingsnake/blob/9d0b231f083cbf195c142b6a1b2ad32b5371ec73/flyingsnake/__main__.py#L23

**Comment by polandar** [comment]
just leaving a note, that i'll work on this one in the next week 👍

**Comment by polandar** [comment]
have you got a sample world file i can run this against?

**Comment by Steffo99** [comment]
yes! i should have uploaded it in the tests directory!

**Comment by Steffo99** [comment]
whoops! it appears to be missing! I'm adding it right now.

**Comment by Steffo99** [comment]
file was added in d50aeb6730b0b67848566617f0de89efd369a7a8! ;)

**Comment by Steffo99** [comment]
This was merged in master with 35a9d8310d06dc40300b88f2c30495e5829deee9.
