### ISSUE TITLE
Update to 1.4

### ISSUE THREAD

**Issue by Steffo99** [Steffo99/flyingsnake#9]

**Comment by Steffo99** [comment]
https://github.com/Steffo99/lihzahrd/releases/tag/2.0.0a1 is available!

Now we just need to wait until TEdit fixes their colours...

**Comment by zosky** [comment]
i'd love a cron job to make a timelapse vid

is [this](https://github.com/TEdit/Terraria-Map-Editor/commit/8a8c5ecdf3593d43bb08faa8965a67fc75a99349) what you were waiting for ?

**Comment by Steffo99** [comment]
I already did that in 1.3!

Check out my other project, powercell, to see how I made one :D

**Comment by Steffo99** [comment]
Also, thanks for the link! :D

It's exactly what I was looking for.

I'll get to updating the color scheme in the next few days.

**Comment by zosky** [comment]
thanks for pointing out powercell. that's basically what i had in mind, but also with a timestamp in the png... that lets them stack up so `ffmpeg` can make a timeLapse. if no changes, `fdups` can rm new renders ... add an mp3 > youtube-upload

**Comment by Steffo99** [comment]
As of [2.0.0a2](https://github.com/Steffo99/flyingsnake/releases/tag/2.0.0a2), flyingsnake is able to parse 1.4 worlds, but some blocks and walls still don't have a color associated (relics, some new walls, etc).

**Comment by zosky** [comment]
success with 2 of 3 worlds. unfortunately, the 3rd -my sons- is the only one i'd like to render. 

i'm getting `ValueError: 562 is not a valid BlockType`. last week i tried adding 562 myself, no luck ... now i see it is in the examples... why still dyeing ?

if having the file helps, let me know

**Comment by Steffo99** [comment]
If you attach the world file I'll gladly have a look :)

**Comment by zosky** [comment]
thanks in advance - hope its an easy one
[world-err526.zip](https://github.com/Steffo99/flyingsnake/files/4848349/world-err526.zip)

**Comment by Steffo99** [comment]
Seems like a bug in lihzahrd. Fixing it there...

**Comment by Steffo99** [comment]
Fixed in https://github.com/Steffo99/lihzahrd/commit/2fa940074cb3224cb8d796e7c8098737ffb5b3cb!
